[features]
seeds = false
skip-lint = false
[programs.localnet]
todo = "HXwWDjX8Bq6nhj6nPqxU4D7Frxk3Rojbqe4LDkGUgMnQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/satyam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
